server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: service-vod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  vod:
    keyId: LTAI4G3xpa14HGX5jS3dy5QD
    keySecret: 0Md4fFv5MY0UPgbyKAwYTa1v5xMuPV
    templateGroupId: f82ce522b7ded4a52f87e8771e4b535b #转码模板组id
    workflowId: 你配置的工作流id #工作流id，和模板组id二选一